reorganized files by moving to a new directory
oracle/nosql-examples pull request #135
Opened 2023-08-23 16:15 UTC by Vandana-Rajamani

## oracle/nosql-examples

Consolidated all sample schemas(BaggageInfo,AcctStreamSchema,GeoJSONSchema) and put them in a new directory SampleSchemas

2023-08-23 16:27 UTC, Vandana-Rajamani commented
Added new directories for sqlexamples

2023-08-24 18:37 UTC, mikebrey commented on examples-nosql-dotnet-sdk/sqlexamples/AddData.cs
> + * Copyright (c) 2018, 2021 Oracle and/or its affiliates. All rights reserved.
correct copyright years

2023-08-24 18:37 UTC, mikebrey commented on examples-nosql-dotnet-sdk/sqlexamples/CreateTable.cs
> + * Copyright (c) 2018, 2021 Oracle and/or its affiliates. All rights reserved.
correct copyright year

2023-08-24 18:38 UTC, mikebrey commented on examples-nosql-dotnet-sdk/sqlexamples/QueryData.cs
> + * Copyright (c) 2018, 2021 Oracle and/or its affiliates. All rights reserved.
correct copyright year

2023-08-24 18:38 UTC, mikebrey commented on examples-nosql-go-sdk/sqlexamples/AddData.go
> +package main
needs copyright and licensing

2023-08-24 18:39 UTC, mikebrey commented on examples-nosql-go-sdk/sqlexamples/CreateTable.go
> +package main
needs copyright and licensing

2023-08-24 18:39 UTC, mikebrey commented on examples-nosql-go-sdk/sqlexamples/QueryData.go
> +package main
needs copyright and licensing

2023-08-24 18:40 UTC, mikebrey commented on examples-nosql-java-sdk/sqlexamples/AddData.java
> +import java.io.File;
needs copyright and licensing

2023-08-24 18:40 UTC, mikebrey commented on examples-nosql-java-sdk/sqlexamples/CreateTable.java
> +import java.io.File;
needs copyright and licensing

2023-08-24 18:40 UTC, mikebrey commented on examples-nosql-java-sdk/sqlexamples/QueryData.java
> +import java.io.File;
needs copyright and licensing

2023-08-24 18:42 UTC, mikebrey requested changes
see comments for changes

2023-08-24 18:42 UTC, mikebrey commented on examples-nosql-node-sdk/sqlexamples/AddData.js
> +'use strict';
needs copyright and licensing

2023-08-24 18:42 UTC, mikebrey commented on examples-nosql-node-sdk/sqlexamples/CreateTable.js
> +'use strict';
needs copyright and licensing

2023-08-24 18:42 UTC, mikebrey commented on examples-nosql-node-sdk/sqlexamples/QueryData.js
> +'use strict';
needs copyright and licensing

2023-08-24 18:42 UTC, mikebrey commented on examples-nosql-python-sdk/sqlexamples/AddData.py
> +import os
needs copyright and licensing

2023-08-24 18:42 UTC, mikebrey commented on examples-nosql-python-sdk/sqlexamples/CreateTable.py
> +import os
needs copyright and licensing

2023-08-24 18:42 UTC, mikebrey commented on examples-nosql-python-sdk/sqlexamples/QueryData.py
> +import os
needs copyright and licensing

2023-08-25 10:41 UTC, Vandana-Rajamani commented
added/corrected copyright and license info in all files

2023-08-25 12:23 UTC, mikebrey commented on examples-nosql-dotnet-sdk/sqlexamples/AddData.cs
> + * Copyright (c) 2023 Oracle and/or its affiliates. All rights reserved.
change copyright to (c) 2022, 2023 
Change on all .NET examples

2023-08-25 12:24 UTC, mikebrey commented on examples-nosql-go-sdk/sqlexamples/AddData.go
> +// Copyright (c) 2023 Oracle and/or its affiliates.
on all GO examples change to   (c) 2020, 2023

2023-08-25 12:26 UTC, mikebrey commented on examples-nosql-java-sdk/sqlexamples/AddData.java
> +/*Copyright (c) 2023 Oracle and/or its affiliates.
change JAva SDK examples to (c) 2020, 2023

2023-08-25 12:27 UTC, mikebrey commented on examples-nosql-node-sdk/sqlexamples/AddData.js
> +/*Copyright (c) 2023 Oracle and/or its affiliates.
change node examples to (c) 2020, 2023

2023-08-25 12:28 UTC, mikebrey commented on examples-nosql-python-sdk/sqlexamples/AddData.py
> +# Copyright (c) 2023 Oracle and/or its affiliates.
change python examples to (c) 2019, 2023

2023-08-25 12:29 UTC, mikebrey requested changes
additional modifications to the copyrights.

2023-08-28 04:10 UTC, Vandana-Rajamani commented
updated copyrights info

2023-08-28 12:20 UTC, mikebrey approved these changes

2023-08-29 06:13 UTC, merged